datasource:
  db_url: "root:238888@tcp(127.0.0.1:3306)/training?charset=utf8mb4&timeout=1s&parseTime=true&interpolateParams=true&loc=Local"
  max_idle: 10
  max_open: 50
  max_idle_time: 30 # 30秒
  max_life_time: 30 # 30秒


log:
  writer: file # console
  level: debug
  caller_skip: 1
  formatter: json
  formatter_config:
    time_fmt: 2006-01-02T15:04:05.999999999Z07:00
    time_key: ts
    level_key: level
    name_key: logger
    caller_key: caller
    message_key: msg
    stacktrace_key: stacktrace
  writer_config: # writer: file 时生效
    filename: common.log
    max_size: 1024                          # 按大小分割时才有效，日志文件最大大小（单位MB）
    max_age: 3                              # 最大日志保留天数
    max_backups: 3                          # 最大日志文件数
    compress: false                         # 日志文件是否压缩
    local_time: true